

DROP TABLE IF EXISTS #Map
CREATE TABLE #Map (
	[StatementItemId] UNIQUEIDENTIFIER,
	[InvoiceId] UNIQUEIDENTIFIER
)

INSERT INTO #Map
SELECT
	si.[StatementItemId],
	NEWID() AS [InvoiceId]
FROM [v_StatementItem] AS si
WHERE 1=1
	AND [InvoiceId] IS NULL
	AND si.Amount = 1.06
	AND si.[PayeeId] = '23148EE8-AFC7-CC8D-3571-E856E7A4FEC3'


DROP TABLE IF EXISTS #InvoiceItem
CREATE TABLE #InvoiceItem (
    [InvoiceId] UNIQUEIDENTIFIER,
    [InvoiceItemId] UNIQUEIDENTIFIER NOT NULL,
    [CategoryId] UNIQUEIDENTIFIER,
    [Description] NVARCHAR(255),
    [Quantity] DECIMAL(18, 3),
    [Amount] DECIMAL(18, 2),
    [DisplayOrder] INT,
    [IsAutoGenerated] BIT,
    CONSTRAINT [PK_InvoiceItem] PRIMARY KEY NONCLUSTERED ([InvoiceItemId])
);


INSERT INTO #InvoiceItem
SELECT 
	m.[InvoiceId],
	NEWID() AS [InvoiceItemId],
	iti.[CategoryId],
	iti.[Description],
	iti.Quantity,
	iti.[Amount],
	iti.[DisplayOrder],
	1 AS [IsAutoGenerated]
FROM [v_StatementItem] AS si
LEFT JOIN [v_InvoiceTemplate] AS it ON it.[PayeeId] = si.[PayeeId]
LEFT JOIN [v_InvoiceTemplateItem] AS iti ON iti.InvoiceTemplateId = it.InvoiceTemplateId
JOIN #Map AS m ON m.[StatementItemId] = si.[StatementItemId]


DROP TABLE IF EXISTS #Invoice
CREATE TABLE #Invoice (
    [UsersId] UNIQUEIDENTIFIER NULL,
    [InvoiceId] UNIQUEIDENTIFIER NOT NULL,
    [PayeeId] UNIQUEIDENTIFIER NOT NULL,
    [InvoiceDate] DATETIME2(0) NOT NULL,
    [DueDate] DATE NULL,
    [InvoiceNumber] NVARCHAR(100) NULL,
    [Amount] DECIMAL(18, 2) NOT NULL,
    [Description] NVARCHAR(1000) NULL,
    [StartDate] DATETIME2(0) NULL,
    [EndDate] DATETIME2(0) NULL,
    [ImageId] UNIQUEIDENTIFIER NULL,
    [AmazonPaymentMethod] NVARCHAR(100) NULL,
    [IsAutoGenerated] BIT NOT NULL DEFAULT 0,
    [IsValidated] BIT NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY NONCLUSTERED ([InvoiceId]),
    CONSTRAINT [UQ_Payee_InvoiceDate_Amount] UNIQUE ([PayeeId], [InvoiceDate], [Amount])
);


INSERT INTO #Invoice
SELECT DISTINCT
	NULL AS [UsersId],
	m.[InvoiceId],
	si.[PayeeId],
	si.[TransactionDate] AS [InvoiceDate],
	NULL AS [DueDate],
	NULL AS [InvoiceNumber],
	si.[Amount] AS [Amount],
	si.[Description] AS [Description],
	NULL AS [StartDate],
	NULL AS [EndDate],
	'2740391C-72F7-3986-62E4-1DA7F8D1C57C' AS [ImageId],
	NULL AS [AmazonPaymentMethod],
	1 AS [IsAutoGenerated],
	NULL AS [IsValidated]
FROM [v_StatementItem] AS si
JOIN #Map AS m ON m.[StatementItemId] = si.[StatementItemId]

INSERT INTO Invoice
SELECT * FROM #Invoice

INSERT INTO InvoiceItem
SELECT * FROM #InvoiceItem








SELECT * FROM Invoice WHERE PayeeId = '23148ee8-afc7-cc8d-3571-e856e7a4fec3' AND Amount = 1.06 AND InvoiceDate = '2025-11-04 00:00:00'
SELECT * FROM #Invoice WHERE PayeeId = '23148ee8-afc7-cc8d-3571-e856e7a4fec3' AND Amount = 1.06 AND InvoiceDate = '2025-11-04 00:00:00'

SELECT * FROM StatementItem  WHERE PayeeId = '23148ee8-afc7-cc8d-3571-e856e7a4fec3' AND Amount = 1.06 AND TransactionDate = '2025-11-04 00:00:00'

SELECT * FROM Statement WHERE StatementId = 'B72842EC-4E98-0CE4-6016-7157C9BEC836'
SELECT * FROM Account WHERE AccountId = 'ED01A6D7-436F-A1B7-8982-99253E6E8719'