services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DOCKER_DB_PASSWORD}"
    ports:
      - "${DOCKER_DB_EXTERNAL_PORT}:${DOCKER_DB_INTERNAL_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\" -b -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
