CREATE TABLE [Invoice] (
    [UsersId] UNIQUEIDENTIFIER NULL,
    [InvoiceId] UNIQUEIDENTIFIER NOT NULL,
    [PayeeId] UNIQUEIDENTIFIER NOT NULL,
    [InvoiceDate] DATETIME2(0) NOT NULL,
    [DueDate] DATE NULL,
    [InvoiceNumber] NVARCHAR(100) NULL,
    [Amount] DECIMAL(18, 2) NOT NULL,
    [Description] NVARCHAR(1000) NULL,
    [StartDate] DATETIME2(0) NULL,
    [EndDate] DATETIME2(0) NULL,
    [ImageId] UNIQUEIDENTIFIER NULL,
    [AmazonPaymentMethod] NVARCHAR(100) NULL,
    [IsAutoGenerated] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_Invoice] PRIMARY KEY NONCLUSTERED ([InvoiceId]),
    CONSTRAINT [FK_Invoice_Users] FOREIGN KEY ([UsersId]) REFERENCES [Users]([UsersId]),
    CONSTRAINT [FK_Invoice_Payee] FOREIGN KEY ([PayeeId]) REFERENCES [Payee]([PayeeId]),
    CONSTRAINT [FK_Invoice_Image] FOREIGN KEY ([ImageId]) REFERENCES [Image]([ImageId]) ON DELETE SET NULL,
    CONSTRAINT [UQ_Payee_InvoiceDate_Amount] UNIQUE ([PayeeId], [InvoiceDate], [Amount])
);

CREATE CLUSTERED INDEX [IX_Invoice_InvoiceDate] ON [Invoice] ([UsersId], [PayeeId], [InvoiceDate], [Amount]);