CREATE TABLE [InvoiceItem] (
    [InvoiceId] UNIQUEIDENTIFIER NOT NULL,
    [InvoiceItemId] UNIQUEIDENTIFIER NOT NULL,
    [CategoryId] UNIQUEIDENTIFIER NOT NULL,
    [Description] NVARCHAR(255) NOT NULL,
    [Quantity] DECIMAL(18, 3) NOT NULL,
    [Amount] DECIMAL(18, 2) NOT NULL,
    [DisplayOrder] INT NOT NULL,
    [IsAutoGenerated] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_InvoiceItem] PRIMARY KEY NONCLUSTERED ([InvoiceItemId]),
    CONSTRAINT [FK_InvoiceItem_Invoice] FOREIGN KEY ([InvoiceId]) REFERENCES [Invoice]([InvoiceId]),
    CONSTRAINT [FK_InvoiceItem_InvoiceItemCategory] FOREIGN KEY ([CategoryId]) REFERENCES [InvoiceItemCategory]([CategoryId])
);

CREATE CLUSTERED INDEX [IX_InvoiceItem_Invoice_Category] ON [InvoiceItem] ([InvoiceId], [DisplayOrder]);