CREATE TABLE [Payee] (
    [PayeeId] UNIQUEIDENTIFIER NOT NULL,
    [PayeeType] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_Payee] PRIMARY KEY NONCLUSTERED ([PayeeId])
);
CREATE CLUSTERED INDEX [IX_Payee_PayeeType] ON [Payee] ([PayeeType]);